apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-newrelic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-newrelic
  template:
    metadata:
      labels:
        app: spring-boot-newrelic
    spec:
      containers:
        - name: spring-boot-newrelic
          image: localhost:5001/spring-boot-newrelic:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NEW_RELIC_APP_NAME
              value: "spring-boot-newrelic"
            - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
              value: "true"
            - name: NEW_RELIC_LICENSE_KEY
              value: "${NEW_RELIC_LICENSE_KEY}"
            - name: MANAGEMENT_NEWRELIC_METRICS_EXPORT_API_KEY
              value: "${MANAGEMENT_NEWRELIC_METRICS_EXPORT_API_KEY}"
            - name: MANAGEMENT_NEWRELIC_METRICS_EXPORT_ACCOUNTID
              value: "${MANAGEMENT_NEWRELIC_METRICS_EXPORT_ACCOUNTID}"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-newrelic-service
spec:
  selector:
    app: spring-boot-newrelic
  ports:
    - port: 8080
      targetPort: 8080
